spring:
  data:
    web:
      sort:
        sort-parameter: sort
      pageable:
        default-page-size: 10
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:~/test
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate.ddl-auto: create-drop
    generate-ddl: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect